#!/usr/bin/env sh

cmd - return : osascript -e 'tell application "kitty" to activate'

cmd - 1: yabai -m space --focus 1
cmd - 2: yabai -m space --focus 2
cmd - 3: yabai -m space --focus 3
cmd - 4: yabai -m space --focus 4
cmd - 5: yabai -m space --focus 5
cmd - 6: yabai -m space --focus 6
cmd - 7: yabai -m space --focus 7
cmd - 8: yabai -m space --focus 8
cmd - 9: yabai -m space --focus 9

fn - h : skhd -k "left"
fn - j : skhd -k "down"
fn - k : skhd -k "up"
fn - l : skhd -k "right"

# reload yabai and skhd
shift + cmd - r : restart
